# Generated by Django 4.2.16 on 2024-11-24 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('openYear', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('plot', models.TextField()),
                ('is_selected', models.BooleanField(default=True)),
                ('poster', models.ImageField(blank=True, upload_to='movies')),
            ],
        ),
        migrations.CreateModel(
            name='Ending',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('like_users', models.ManyToManyField(default=None, related_name='like_endings', to=settings.AUTH_USER_MODEL)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movie', to='moviearticles.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ending_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviearticles.ending')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
